config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies do
    collection do
      get "search"
    end
    resources :reviews
  end

  root "movies#index"

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	searchkick
	has_many :reviews, dependent: :destroy
	belongs_to :user

	has_attached_file :image, styles: { medium: "400x600#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :movie	
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :info, :warning
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

	def search
		if params[:search].present?
			@movies = Movie.search(params[:search])
		else
			@movies = Movie.all
		end
	end

	def index
		@movies = Movie.all
	end

	def show
		@movie = Movie.find(params[:id])
		@reviews = @movie.reviews

		if @reviews.blank?
			@avg_review = 0
		else
			@avg_review = @reviews.average(:rating).round(2)
		end
	end

	def new
		@movie = current_user.movies.build
	end

	def create
		@movie = current_user.movies.build(movie_params)

		if @movie.save
			redirect_to movies_path, info: "Successfully posted a new movie."
		else
			render :new
		end
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		@movie = Movie.find(params[:id])

		if @movie.update(movie_params)
			redirect_to movies_path
		else
			render :edit
		end
	end

	def destroy
		@movie = Movie.find(params[:id])
		@movie.destroy
		redirect_to movies_path
	end

	private

	def movie_params
		params.require(:movie).permit(:title, :description, :length, :director, :rating, :image)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]

	def new
		@movie = Movie.find(params[:movie_id])
		@review = @movie.reviews.new
	end

	def create
		@movie = Movie.find(params[:movie_id])
		@review = @movie.reviews.build(review_params)
		@review.user_id = current_user.id

		if @review.save
			redirect_to movie_path(@movie, @review), warning: "New review has been posted successfully."
		else
			render :new
		end
	end

	private

	def review_params
		params.require(:review).permit(:rating, :comment)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
	end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">

		<div class="navbar-header">
			<%= link_to "Movie Reviews", root_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<% if !user_signed_in? %>
					<li>
						<%= link_to "Sign up", new_user_registration_path %>
					</li>
					<li>
						<%= link_to "Sign in", new_user_session_path %>
					</li>
				<% else %>
					<li>
						<%= link_to "Add New Movie", new_movie_path %>
					</li>
					<li>
						<%= link_to "Account", edit_user_registration_path %>
					</li>
					<li>
						<%= link_to "Logout", destroy_user_session_path, method: :delete %>
					</li>
				<% end %>
			</ul>
			<%= form_tag search_movies_path, method: :get, class: "navbar-form navbar-right", role: "search" do %>
        <p>
          <%= text_field_tag :search, params[:search], class: "form-control" %>
          <%= submit_tag "Search", name: nil, class: "btn btn-default" %>
        </p>
      <% end %>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mr1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="row">
		<div class="col-md-12">
			<div class="container">
				<%= render "common/navbar" %>
				<%= notice_message %>
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>

app/views/movies/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>Edit moive</h2>
		<%= simple_form_for @movie do |f| %>
			<div>
				<%= f.input :title %>
			</div>
			<div>
				<%= f.input :description %>
			</div>
			<div>
				<%= f.input :length %>
			</div>
			<div>
				<%= f.input :director %>
			</div>
			<div>
				<%= f.input :rating %>
			</div>
			<div>
				<%= f.input :image, as: :file %>
			</div>
			<div>
				<%= f.button :submit, data: {disable_with: "Submitting..."} %>
				<%= link_to "Back", movies_path, class: "btn btn-default" %>
			</div>
		<% end %>
	</div>
</div>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
	<div class="jumbotron">
		<h1>Your Favorite Movies Reviewed</h1>
		<p>Current movie reviews and ratings from critics on all of the latest movies.</p>
		<p>
			<%= link_to "Sign Up To Write A Review", new_user_registration_path, class: "btn btn-primary btn-lg" %>
		</p>
	</div>
<% end %>

<div class="row">
	<% @movies.each do |movie| %>
		<div class="col-md-3 col-sm-6">
			<div class="thumbnail">
				<%= link_to movie do %>
					<%= image_tag(movie.image.url(:medium)) %>
				<% end %> 
			</div>
		</div>
	<% end %>
</div>

app/views/movies/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>Add new moive</h2>
		<%= simple_form_for @movie do |f| %>
			<div>
				<%= f.input :title %>
			</div>
			<div>
				<%= f.input :description %>
			</div>
			<div>
				<%= f.input :length %>
			</div>
			<div>
				<%= f.input :director %>
			</div>
			<div>
				<%= f.input :rating %>
			</div>
			<div>
				<%= f.input :image, as: :file %>
			</div>
			<div>
				<%= f.button :submit, data: {disable_with: "Submitting..."} %>
				<%= link_to "Back", movies_path, class: "btn btn-default" %>
			</div>
		<% end %>
	</div>
</div>

app/views/movies/search.html.erb
<div class="row">
	<% @movies.each do |movie| %>
		<div class="col-md-3 col-sm-6">
			<div class="thumbnail">
				<%= link_to movie do %>
					<%= image_tag(movie.image.url(:medium)) %>
				<% end %> 
			</div>
		</div>
	<% end %>
</div>

app/views/movies/show.html.erb
<div class="panel panel-default">
	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
				<%= image_tag @movie.image.url(:medium) %>

				<div class="star-rating" data-score= <%= @avg_review %> ></div>
        <em><%= "#{@reviews.length} reviews" %></em>
        
				<table class="table">
					<tbody>
						<tr>
							<td><strong>Title: </strong></td>
							<td><%= @movie.title %></td>
						</tr>
						<tr>
							<td><strong>Description: </strong></td>
							<td><%= @movie.description %></td>
						</tr>
						<tr>
							<td><strong>Movie Length: </strong></td>
							<td><%= @movie.length %></td>
						</tr>
						<tr>
							<td><strong>Director: </strong></td>
							<td><%= @movie.director %></td>
						</tr>
						<tr>
							<td><strong>Rating: </strong></td>
							<td><%= @movie.rating %></td>
						</tr>
					</tbody>
				</table>
				<%= link_to "Write a review", new_movie_review_path(@movie, @review) %>
			</div>
			<div class="col-md-7 col-md-offset-1">
				<h1><%= @movie.title %></h1>
				<p><%= @movie.description %></p>
				
				<% if @reviews.blank? %>
					<h3>No reviews just yet, would you like to add the first!</h3>
	          <%= link_to "Write Review", new_movie_review_path(@movie), class: "btn btn-danger" %>
				<% else %>
					<% @reviews.each do |review| %>
						<div class="star-rating" data-score= <%= review.rating %> ></div>
						<br>
						<p><%= review.comment %></p>
						<hr>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>

<div>
	<%= link_to "Edit", edit_movie_path(@movie) %> |
	<%= link_to "Remove", movie_path(@movie), method: :delete, data: {confirm: "Sure?"} %>
</div>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>Add new review</h2>
		<%= simple_form_for [@review.movie, @review] do |f| %>
			<div>
				<div id="star-rating"></div>
				<%= f.input :comment %>
			</div>
			<div>
				<%= f.button :submit, data: {disable_with: "Submitting..."} %>
				<%= link_to "Back", movie_path(@movie), class: "btn btn-default" %>
			</div>
		<% end %>
	</div>
</div>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: "review[rating]"
  });
</script>